name:
  Tests for REST API endpoints for issues

on:
  push

env:
  github_token: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest --alluredir reports
      - name: Save results
        uses: actions/upload-artifact@v3
        with: 
          name: reports
          path:
            reports
          retention-days: 1
        
  prepare_reports:

    runs-on: macos-latest
    needs: test
    name: creating_report

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: brew install allure
      - name: Download artifact
        uses: actions/download-artifact@v4
      - run: allure generate -c reports -o _site
      - name: Save reports
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1

  show_reports:

    runs-on: ubuntu-latest
    needs: prepare_reports
    name: screening_report

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
