name:
  Tests for REST API endpoints for issues

on:
  push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest ${{ secrets.GITHUB_TOKEN }}
      - name: Save results
        uses: actions/upload-artifact@v3
        with: 
          name: reports
          path:
            reports
          retention-days: 1
        
  prepare_reports:
    runs-on: macos-latest
    needs: test
    name: Creating report
    steps:
      - uses: actions/setup-java@v3
        with:
          distibution: 'microsoft'
          java-version: '17'
      - run: brew install allure
      - name: Download artifact
        uses: actions/download-artifact@v3
      - run: allure generate -c reports -o _site
      - name: Save reports
        uses: actions/upload-artifact@v3
        with: 
          name: _site
          path:
            _site
          retention-days: 1

  show_reports:
    runs-on: macos-latest
    needs: prepare_reports
    name: Screening report
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1.2.9
      
